 const countriesData = [
  {
    name: "Afghanistan",
    regions: ["asia", "", "", ""],
    iso2: "af",
    countryCode: 93,
    dialCode: 93,
    format: "+.. ... ... ... ... ..",
    priority: 0,
    n: "Afghanistan (‫افغانستان‬‎)(+93‬‎)",
    mainCode: null,
  },
  {
    name: "Albania",
    regions: ["europe", "", "", ""],
    iso2: "al",
    countryCode: 355,
    dialCode: 355,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Albania (Shqipëri)(+355)",
    mainCode: null,
  },
  {
    name: "Algeria",
    regions: ["africa", "north-africa", "", ""],
    iso2: "dz",
    countryCode: 213,
    dialCode: 213,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Algeria (‫الجزائر‬‎)(+213‬‎)",
    mainCode: null,
  },
  {
    name: "Andorra",
    regions: ["europe", "", "", ""],
    iso2: "ad",
    countryCode: 376,
    dialCode: 376,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Andorra(+376)",
    mainCode: null,
  },
  {
    name: "Angola",
    regions: ["africa", "", "", ""],
    iso2: "ao",
    countryCode: 244,
    dialCode: 244,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Angola(+244)",
    mainCode: null,
  },
  {
    name: "Antigua and Barbuda",
    regions: ["america", "carribean", "", ""],
    iso2: "ag",
    countryCode: 1268,
    dialCode: 1268,
    format: "+.... ... ... ... ... ..",
    priority: 0,
    n: "Antigua and Barbuda(+1268)",
    mainCode: null,
  },
  {
    name: "Argentina",
    regions: ["america", "south-america", "", ""],
    iso2: "ar",
    countryCode: 54,
    dialCode: 54,
    format: "+.. (..) ........",
    priority: 0,
    n: "Argentina(+54)",
    mainCode: true,
  },
  {
    name: "Armenia",
    regions: ["asia", "ex-ussr", "", ""],
    iso2: "am",
    countryCode: 374,
    dialCode: 374,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Armenia (Հայաստան)(+374)",
    mainCode: null,
  },
  {
    name: "Aruba",
    regions: ["america", "carribean", "", ""],
    iso2: "aw",
    countryCode: 297,
    dialCode: 297,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Aruba(+297)",
    mainCode: null,
  },
  {
    name: "Australia",
    regions: ["oceania", "", "", ""],
    iso2: "au",
    countryCode: 61,
    dialCode: 61,
    format: "+.. (..) .... ....",
    priority: 0,
    n: "Australia(+61)",
    mainCode: true,
  },
  {
    name: "Austria",
    regions: ["europe", "eu-union", "", ""],
    iso2: "at",
    countryCode: 43,
    dialCode: 43,
    format: "+.. ... ... ... ... ..",
    priority: 0,
    n: "Austria (Österreich)(+43)",
    mainCode: null,
  },
  {
    name: "Azerbaijan",
    regions: ["asia", "ex-ussr", "", ""],
    iso2: "az",
    countryCode: 994,
    dialCode: 994,
    format: "+... (..) ... .. ..",
    priority: 0,
    n: "Azerbaijan (Azərbaycan)(+994)",
    mainCode: null,
  },
  {
    name: "Bahamas",
    regions: ["america", "carribean", "", ""],
    iso2: "bs",
    countryCode: 1242,
    dialCode: 1242,
    format: "+.... ... ... ... ... ..",
    priority: 0,
    n: "Bahamas(+1242)",
    mainCode: null,
  },
  {
    name: "Bahrain",
    regions: ["middle-east", "", "", ""],
    iso2: "bh",
    countryCode: 973,
    dialCode: 973,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Bahrain (‫البحرين‬‎)(‫+973‬‎)",
    mainCode: null,
  },
  {
    name: "Bangladesh",
    regions: ["asia", "", "", ""],
    iso2: "bd",
    countryCode: 880,
    dialCode: 880,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Bangladesh (বাংলাদেশ)(+880)",
    mainCode: null,
  },
  {
    name: "Barbados",
    regions: ["america", "carribean", "", ""],
    iso2: "bb",
    countryCode: 1246,
    dialCode: 1246,
    format: "+.... ... ... ... ... ..",
    priority: 0,
    n: "Barbados(+1246)",
    mainCode: null,
  },
  {
    name: "Belarus",
    regions: ["europe", "ex-ussr", "", ""],
    iso2: "by",
    countryCode: 375,
    dialCode: 375,
    format: "+... (..) ... .. ..",
    priority: 0,
    n: "Belarus (Беларусь)(+375)",
    mainCode: null,
  },
  {
    name: "Belgium",
    regions: ["europe", "eu-union", "", ""],
    iso2: "be",
    countryCode: 32,
    dialCode: 32,
    format: "+.. ... .. .. ..",
    priority: 0,
    n: "Belgium (België)(+32)",
    mainCode: null,
  },
  {
    name: "Belize",
    regions: ["america", "central-america", "", ""],
    iso2: "bz",
    countryCode: 501,
    dialCode: 501,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Belize(+501)",
    mainCode: null,
  },
  {
    name: "Benin",
    regions: ["africa", "", "", ""],
    iso2: "bj",
    countryCode: 229,
    dialCode: 229,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Benin (Bénin)(+229)",
    mainCode: null,
  },
  {
    name: "Bhutan",
    regions: ["asia", "", "", ""],
    iso2: "bt",
    countryCode: 975,
    dialCode: 975,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Bhutan (འབྲུག)(+975)",
    mainCode: null,
  },
  {
    name: "Bolivia",
    regions: ["america", "south-america", "", ""],
    iso2: "bo",
    countryCode: 591,
    dialCode: 591,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Bolivia(+591)",
    mainCode: null,
  },
  {
    name: "Bosnia and Herzegovina",
    regions: ["europe", "ex-yugos", "", ""],
    iso2: "ba",
    countryCode: 387,
    dialCode: 387,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Bosnia and Herzegovina (Босна и Херцеговина)(+387)",
    mainCode: null,
  },
  {
    name: "Botswana",
    regions: ["africa", "", "", ""],
    iso2: "bw",
    countryCode: 267,
    dialCode: 267,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Botswana(+267)",
    mainCode: null,
  },
  {
    name: "Brazil",
    regions: ["america", "south-america", "", ""],
    iso2: "br",
    countryCode: 55,
    dialCode: 55,
    format: "+.. (..) .........",
    priority: 0,
    n: "Brazil (Brasil)(+55)",
    mainCode: null,
  },
  {
    name: "British Indian Ocean Territory",
    regions: ["asia", "", "", ""],
    iso2: "io",
    countryCode: 246,
    dialCode: 246,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "British Indian Ocean Territory(+246)",
    mainCode: null,
  },
  {
    name: "Brunei",
    regions: ["asia", "", "", ""],
    iso2: "bn",
    countryCode: 673,
    dialCode: 673,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Brunei(+673)",
    mainCode: null,
  },
  {
    name: "Bulgaria",
    regions: ["europe", "eu-union", "", ""],
    iso2: "bg",
    countryCode: 359,
    dialCode: 359,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Bulgaria (България)(+359)",
    mainCode: null,
  },
  {
    name: "Burkina Faso",
    regions: ["africa", "", "", ""],
    iso2: "bf",
    countryCode: 226,
    dialCode: 226,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Burkina Faso(+226)",
    mainCode: null,
  },
  {
    name: "Burundi",
    regions: ["africa", "", "", ""],
    iso2: "bi",
    countryCode: 257,
    dialCode: 257,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Burundi (Uburundi)(+257)",
    mainCode: null,
  },
  {
    name: "Cambodia",
    regions: ["asia", "", "", ""],
    iso2: "kh",
    countryCode: 855,
    dialCode: 855,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Cambodia (កម្ពុជា)(+855)",
    mainCode: null,
  },
  {
    name: "Cameroon",
    regions: ["africa", "", "", ""],
    iso2: "cm",
    countryCode: 237,
    dialCode: 237,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Cameroon (Cameroun)(+237)",
    mainCode: null,
  },
  {
    name: "Canada",
    regions: ["america", "north-america", "", ""],
    iso2: "ca",
    countryCode: 1,
    dialCode: 1,
    format: "+. (...) ...-....",
    priority: 1,
    n: "Canada(+1)",
    mainCode: true,
  },
  {
    name: "Cape Verde",
    regions: ["africa", "", "", ""],
    iso2: "cv",
    countryCode: 238,
    dialCode: 238,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Cape Verde (Kabu Verdi)(+238)",
    mainCode: null,
  },
  {
    name: "Caribbean Netherlands",
    regions: ["america", "carribean", "", ""],
    iso2: "bq",
    countryCode: 599,
    dialCode: 599,
    format: "+... ... ... ... ... ..",
    priority: 1,
    n: "Caribbean Netherlands(+599)",
    mainCode: null,
  },
  {
    name: "Central African Republic",
    regions: ["africa", "", "", ""],
    iso2: "cf",
    countryCode: 236,
    dialCode: 236,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Central African Republic (République Centrafricaine)(+236)",
    mainCode: null,
  },
  {
    name: "Chad",
    regions: ["africa", "", "", ""],
    iso2: "td",
    countryCode: 235,
    dialCode: 235,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Chad (Tchad)(+235)",
    mainCode: null,
  },
  {
    name: "Chile",
    regions: ["america", "south-america", "", ""],
    iso2: "cl",
    countryCode: 56,
    dialCode: 56,
    format: "+.. ... ... ... ... ..",
    priority: 0,
    n: "Chile (+56)",
    mainCode: null,
  },
  {
    name: "China",
    regions: ["asia", "", "", ""],
    iso2: "cn",
    countryCode: 86,
    dialCode: 86,
    format: "+.. ..-.........",
    priority: 0,
    n: "China (中国)(+86)",
    mainCode: null,
  },
  {
    name: "Colombia",
    regions: ["america", "south-america", "", ""],
    iso2: "co",
    countryCode: 57,
    dialCode: 57,
    format: "+.. ... ... ....",
    priority: 0,
    n: "Colombia (+57)",
    mainCode: null,
  },
  {
    name: "Comoros",
    regions: ["africa", "", "", ""],
    iso2: "km",
    countryCode: 269,
    dialCode: 269,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Comoros (‫جزر القمر‬‎)(+269)",
    mainCode: null,
  },
  {
    name: "Congo",
    regions: ["africa", "", "", ""],
    iso2: "cd",
    countryCode: 243,
    dialCode: 243,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Congo (DRC) (Jamhuri ya Kidemokrasia ya Kongo)(+242)",
    mainCode: null,
  },
  {
    name: "Congo",
    regions: ["africa", "", "", ""],
    iso2: "cg",
    countryCode: 242,
    dialCode: 242,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Congo (Republic) (Congo-Brazzaville)(+242)",
    mainCode: null,
  },
  {
    name: "Costa Rica",
    regions: ["america", "central-america", "", ""],
    iso2: "cr",
    countryCode: 506,
    dialCode: 506,
    format: "+... ....-....",
    priority: 0,
    n: "Costa Rica (+506)",
    mainCode: null,
  },
  {
    name: "Côte d’Ivoire",
    regions: ["africa", "", "", ""],
    iso2: "ci",
    countryCode: 225,
    dialCode: 225,
    format: "+... .. .. .. ..",
    priority: 0,
    n: "Côte d’Ivoire (+225)",
    mainCode: null,
  },
  {
    name: "Croatia",
    regions: ["europe", "eu-union", "ex-yugos", ""],
    iso2: "hr",
    countryCode: 385,
    dialCode: 385,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Croatia (Hrvatska)(+385)",
    mainCode: null,
  },
  {
    name: "Cuba",
    regions: ["america", "carribean", "", ""],
    iso2: "cu",
    countryCode: 53,
    dialCode: 53,
    format: "+.. ... ... ... ... ..",
    priority: 0,
    n: "Cuba (+53)",
    mainCode: null,
  },
  {
    name: "Curaçao",
    regions: ["america", "carribean", "", ""],
    iso2: "cw",
    countryCode: 599,
    dialCode: 599,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Curaçao (+599)",
    mainCode: null,
  },
  {
    name: "Cyprus",
    regions: ["europe", "eu-union", "", ""],
    iso2: "cy",
    countryCode: 357,
    dialCode: 357,
    format: "+... .. ......",
    priority: 0,
    n: "Cyprus (Κύπρος)(+357)",
    mainCode: null,
  },
  {
    name: "Czech Republic",
    regions: ["europe", "eu-union", "", ""],
    iso2: "cz",
    countryCode: 420,
    dialCode: 420,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Czech Republic (Česká republika)(+420)",
    mainCode: null,
  },
  {
    name: "Denmark",
    regions: ["europe", "eu-union", "baltic", ""],
    iso2: "dk",
    countryCode: 45,
    dialCode: 45,
    format: "+.. .. .. .. ..",
    priority: 0,
    n: "Denmark (Danmark)(+45)",
    mainCode: null,
  },
  {
    name: "Djibouti",
    regions: ["africa", "", "", ""],
    iso2: "dj",
    countryCode: 253,
    dialCode: 253,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Djibouti (+253)",
    mainCode: null,
  },
  {
    name: "Dominica",
    regions: ["america", "carribean", "", ""],
    iso2: "dm",
    countryCode: 1767,
    dialCode: 1767,
    format: "+.... ... ... ... ... ..",
    priority: 0,
    n: "Dominica (+1767)",
    mainCode: null,
  },
  {
    name: "Dominican Republic",
    regions: ["america", "carribean", "", ""],
    iso2: "do",
    countryCode: 1,
    dialCode: 1,
    format: "+. ... ... ... ... ..",
    priority: 2,
    n: "Dominican Republic(República Dominicana)(+1809)",
    mainCode: true,
  },
  {
    name: "Ecuador",
    regions: ["america", "south-america", "", ""],
    iso2: "ec",
    countryCode: 593,
    dialCode: 593,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Ecuador (+593)",
    mainCode: null,
  },
  {
    name: "Egypt",
    regions: ["africa", "north-africa", "", ""],
    iso2: "eg",
    countryCode: 20,
    dialCode: 20,
    format: "+.. ... ... ... ... ..",
    priority: 0,
    n: "Egypt (‫مصر‬‎)(+20)",
    mainCode: null,
  },
  {
    name: "El Salvador",
    regions: ["america", "central-america", "", ""],
    iso2: "sv",
    countryCode: 503,
    dialCode: 503,
    format: "+... ....-....",
    priority: 0,
    n: "El Salvador (+503)",
    mainCode: null,
  },
  {
    name: "Equatorial Guinea",
    regions: ["africa", "", "", ""],
    iso2: "gq",
    countryCode: 240,
    dialCode: 240,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Equatorial Guinea (Guinea Ecuatorial)(+240)",
    mainCode: null,
  },
  {
    name: "Eritrea",
    regions: ["africa", "", "", ""],
    iso2: "er",
    countryCode: 291,
    dialCode: 291,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Eritrea (+291)",
    mainCode: null,
  },
  {
    name: "Estonia",
    regions: ["europe", "eu-union", "ex-ussr", "baltic"],
    iso2: "ee",
    countryCode: 372,
    dialCode: 372,
    format: "+... .... ......",
    priority: 0,
    n: "Estonia (Eesti)(+372)",
    mainCode: null,
  },
  {
    name: "Ethiopia",
    regions: ["africa", "", "", ""],
    iso2: "et",
    countryCode: 251,
    dialCode: 251,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Ethiopia (+251)",
    mainCode: null,
  },
  {
    name: "Fiji",
    regions: ["oceania", "", "", ""],
    iso2: "fj",
    countryCode: 679,
    dialCode: 679,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Fiji (+679)",
    mainCode: null,
  },
  {
    name: "Finland",
    regions: ["europe", "eu-union", "baltic", ""],
    iso2: "fi",
    countryCode: 358,
    dialCode: 358,
    format: "+... .. ... .. ..",
    priority: 0,
    n: "Finland (Suomi)(+358)",
    mainCode: null,
  },
  {
    name: "France",
    regions: ["europe", "eu-union", "", ""],
    iso2: "fr",
    countryCode: 33,
    dialCode: 33,
    format: "+.. . .. .. .. ..",
    priority: 0,
    n: "France (+33)",
    mainCode: null,
  },
  {
    name: "French Guiana",
    regions: ["america", "south-america", "", ""],
    iso2: "gf",
    countryCode: 594,
    dialCode: 594,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "French Guiana (Guyane française)(+594)",
    mainCode: null,
  },
  {
    name: "French Polynesia",
    regions: ["oceania", "", "", ""],
    iso2: "pf",
    countryCode: 689,
    dialCode: 689,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "French Polynesia (Polynésie française)(+689)",
    mainCode: null,
  },
  {
    name: "Gabon",
    regions: ["africa", "", "", ""],
    iso2: "ga",
    countryCode: 241,
    dialCode: 241,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Gabon (+241)",
    mainCode: null,
  },
  {
    name: "Gambia",
    regions: ["africa", "", "", ""],
    iso2: "gm",
    countryCode: 220,
    dialCode: 220,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Gambia (+220)",
    mainCode: null,
  },
  {
    name: "Georgia",
    regions: ["asia", "ex-ussr", "", ""],
    iso2: "ge",
    countryCode: 995,
    dialCode: 995,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Georgia (საქართველო)(+995)",
    mainCode: null,
  },
  {
    name: "Germany",
    regions: ["europe", "eu-union", "baltic", ""],
    iso2: "de",
    countryCode: 49,
    dialCode: 49,
    format: "+.. .... ........",
    priority: 0,
    n: "Germany (Deutschland)(+49)",
    mainCode: null,
  },
  {
    name: "Ghana",
    regions: ["africa", "", "", ""],
    iso2: "gh",
    countryCode: 233,
    dialCode: 233,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Ghana (Gaana)(+233)",
    mainCode: null,
  },
  {
    name: "Greece",
    regions: ["europe", "eu-union", "", ""],
    iso2: "gr",
    countryCode: 30,
    dialCode: 30,
    format: "+.. ... ... ... ... ..",
    priority: 0,
    n: "Greece (Ελλάδα)(+30)",
    mainCode: null,
  },
  {
    name: "Grenada",
    regions: ["america", "carribean", "", ""],
    iso2: "gd",
    countryCode: 1473,
    dialCode: 1473,
    format: "+.... ... ... ... ... ..",
    priority: 0,
    n: "Grenada (+1473)",
    mainCode: null,
  },
  {
    name: "Guadeloupe",
    regions: ["america", "carribean", "", ""],
    iso2: "gp",
    countryCode: 590,
    dialCode: 590,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Guadeloupe (+590)",
    mainCode: null,
  },
  {
    name: "Guam",
    regions: ["oceania", "", "", ""],
    iso2: "gu",
    countryCode: 1671,
    dialCode: 1671,
    format: "+.... ... ... ... ... ..",
    priority: 0,
    n: "Guam (+1671)",
    mainCode: null,
  },
  {
    name: "Guatemala",
    regions: ["america", "central-america", "", ""],
    iso2: "gt",
    countryCode: 502,
    dialCode: 502,
    format: "+... ....-....",
    priority: 0,
    n: "Guatemala (+502)",
    mainCode: null,
  },
  {
    name: "Guinea",
    regions: ["africa", "", "", ""],
    iso2: "gn",
    countryCode: 224,
    dialCode: 224,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Guinea (Guinée)(+224)",
    mainCode: null,
  },
  {
    name: "Guinea-Bissau",
    regions: ["africa", "", "", ""],
    iso2: "gw",
    countryCode: 245,
    dialCode: 245,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Guinea-Bissau (Guiné Bissau)(+245)",
    mainCode: null,
  },
  {
    name: "Guyana",
    regions: ["america", "south-america", "", ""],
    iso2: "gy",
    countryCode: 592,
    dialCode: 592,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Guyana (+592)",
    mainCode: null,
  },
  {
    name: "Haiti",
    regions: ["america", "carribean", "", ""],
    iso2: "ht",
    countryCode: 509,
    dialCode: 509,
    format: "+... ....-....",
    priority: 0,
    n: "Haiti (+509)",
    mainCode: null,
  },
  {
    name: "Honduras",
    regions: ["america", "central-america", "", ""],
    iso2: "hn",
    countryCode: 504,
    dialCode: 504,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Honduras (+504)",
    mainCode: null,
  },
  {
    name: "Hong Kong",
    regions: ["asia", "", "", ""],
    iso2: "hk",
    countryCode: 852,
    dialCode: 852,
    format: "+... .... ....",
    priority: 0,
    n: "Hong Kong (香港)(+852)",
    mainCode: null,
  },
  {
    name: "Hungary",
    regions: ["europe", "eu-union", "", ""],
    iso2: "hu",
    countryCode: 36,
    dialCode: 36,
    format: "+.. ... ... ... ... ..",
    priority: 0,
    n: "Hungary (Magyarország)(+36)",
    mainCode: null,
  },
  {
    name: "Iceland",
    regions: ["europe", "", "", ""],
    iso2: "is",
    countryCode: 354,
    dialCode: 354,
    format: "+... ... ....",
    priority: 0,
    n: "Iceland (Ísland)(+354)",
    mainCode: null,
  },
  {
    name: "India",
    regions: ["asia", "", "", ""],
    iso2: "in",
    countryCode: 91,
    dialCode: 91,
    format: "+.. .....-.....",
    priority: 0,
    n: "India (भारत)(+91)",
    mainCode: null,
  },
  {
    name: "Indonesia",
    regions: ["asia", "", "", ""],
    iso2: "id",
    countryCode: 62,
    dialCode: 62,
    format: "+.. ... ... ... ... ..",
    priority: 0,
    n: "Indonesia (+62)",
    mainCode: null,
  },
  {
    name: "Iran",
    regions: ["middle-east", "", "", ""],
    iso2: "ir",
    countryCode: 98,
    dialCode: 98,
    format: "+.. ... ... ....",
    priority: 0,
    n: "Iran (‫ایران‬‎)(+98‬‎)",
    mainCode: null,
  },
  {
    name: "Iraq",
    regions: ["middle-east", "", "", ""],
    iso2: "iq",
    countryCode: 964,
    dialCode: 964,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Iraq (‫العراق‬‎)(+964‬‎)",
    mainCode: null,
  },
  {
    name: "Ireland",
    regions: ["europe", "eu-union", "", ""],
    iso2: "ie",
    countryCode: 353,
    dialCode: 353,
    format: "+... .. .......",
    priority: 0,
    n: "Ireland (+353)",
    mainCode: null,
  },
  {
    name: "Israel",
    regions: ["middle-east", "", "", ""],
    iso2: "il",
    countryCode: 972,
    dialCode: 972,
    format: "+... ... ... ....",
    priority: 0,
    n: "Israel (‫ישראל‬‎)(+972‬‎)",
    mainCode: null,
  },
  {
    name: "Italy",
    regions: ["europe", "eu-union", "", ""],
    iso2: "it",
    countryCode: 39,
    dialCode: 39,
    format: "+.. ... .......",
    priority: 0,
    n: "Italy (Italia)(+39)",
    mainCode: null,
  },
  {
    name: "Jamaica",
    regions: ["america", "carribean", "", ""],
    iso2: "jm",
    countryCode: 1876,
    dialCode: 1876,
    format: "+.... ... ... ... ... ..",
    priority: 0,
    n: "Jamaica (+1876)",
    mainCode: null,
  },
  {
    name: "Japan",
    regions: ["asia", "", "", ""],
    iso2: "jp",
    countryCode: 81,
    dialCode: 81,
    format: "+.. .. .... ....",
    priority: 0,
    n: "Japan (日本)(+81)",
    mainCode: null,
  },
  {
    name: "Jordan",
    regions: ["middle-east", "", "", ""],
    iso2: "jo",
    countryCode: 962,
    dialCode: 962,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Jordan (‫الأردن‬‎)(+962‬‎)",
    mainCode: null,
  },
  {
    name: "Kazakhstan",
    regions: ["asia", "ex-ussr", "", ""],
    iso2: "kz",
    countryCode: 7,
    dialCode: 7,
    format: "+. ... ...-..-..",
    priority: 1,
    n: "Kazakhstan (Казахстан)(+7)",
    mainCode: true,
  },
  {
    name: "Kenya",
    regions: ["africa", "", "", ""],
    iso2: "ke",
    countryCode: 254,
    dialCode: 254,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Kenya (+254)",
    mainCode: null,
  },
  {
    name: "Kiribati",
    regions: ["oceania", "", "", ""],
    iso2: "ki",
    countryCode: 686,
    dialCode: 686,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Kiribati (+686)",
    mainCode: null,
  },
  {
    name: "Kosovo",
    regions: ["europe", "ex-yugos", "", ""],
    iso2: "xk",
    countryCode: 383,
    dialCode: 383,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Kosovo (Kosovë)(+383)",
    mainCode: null,
  },
  {
    name: "Kuwait",
    regions: ["middle-east", "", "", ""],
    iso2: "kw",
    countryCode: 965,
    dialCode: 965,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Kuwait (‫الكويت‬‎)(+965‬‎)",
    mainCode: null,
  },
  {
    name: "Kyrgyzstan",
    regions: ["asia", "ex-ussr", "", ""],
    iso2: "kg",
    countryCode: 996,
    dialCode: 996,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Kyrgyzstan (Кыргызстан)(+996)",
    mainCode: null,
  },
  {
    name: "Laos",
    regions: ["asia", "", "", ""],
    iso2: "la",
    countryCode: 856,
    dialCode: 856,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Laos (ລາວ)(+856)",
    mainCode: null,
  },
  {
    name: "Latvia",
    regions: ["europe", "eu-union", "ex-ussr", "baltic"],
    iso2: "lv",
    countryCode: 371,
    dialCode: 371,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Latvia (Latvija)(+371)",
    mainCode: null,
  },
  {
    name: "Lebanon",
    regions: ["middle-east", "", "", ""],
    iso2: "lb",
    countryCode: 961,
    dialCode: 961,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Lebanon (‫لبنان‬‎)(+961‬‎)",
    mainCode: null,
  },
  {
    name: "Lesotho",
    regions: ["africa", "", "", ""],
    iso2: "ls",
    countryCode: 266,
    dialCode: 266,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Lesotho (+266)",
    mainCode: null,
  },
  {
    name: "Liberia",
    regions: ["africa", "", "", ""],
    iso2: "lr",
    countryCode: 231,
    dialCode: 231,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Liberia (+231)",
    mainCode: null,
  },
  {
    name: "Libya",
    regions: ["africa", "north-africa", "", ""],
    iso2: "ly",
    countryCode: 218,
    dialCode: 218,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Libya (‫ليبيا‬‎)(+218‬‎)",
    mainCode: null,
  },
  {
    name: "Liechtenstein",
    regions: ["europe", "", "", ""],
    iso2: "li",
    countryCode: 423,
    dialCode: 423,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Liechtenstein (+423)",
    mainCode: null,
  },
  {
    name: "Lithuania",
    regions: ["europe", "eu-union", "ex-ussr", "baltic"],
    iso2: "lt",
    countryCode: 370,
    dialCode: 370,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Lithuania (Lietuva)(+370)",
    mainCode: null,
  },
  {
    name: "Luxembourg",
    regions: ["europe", "eu-union", "", ""],
    iso2: "lu",
    countryCode: 352,
    dialCode: 352,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Luxembourg (+352)",
    mainCode: null,
  },
  {
    name: "Macau",
    regions: ["asia", "", "", ""],
    iso2: "mo",
    countryCode: 853,
    dialCode: 853,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Macau (澳門)(+853)",
    mainCode: null,
  },
  {
    name: "Macedonia",
    regions: ["europe", "ex-yugos", "", ""],
    iso2: "mk",
    countryCode: 389,
    dialCode: 389,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Macedonia (FYROM) (Македонија)(+389)",
    mainCode: null,
  },
  {
    name: "Madagascar",
    regions: ["africa", "", "", ""],
    iso2: "mg",
    countryCode: 261,
    dialCode: 261,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Madagascar (Madagasikara)(+261)",
    mainCode: null,
  },
  {
    name: "Malawi",
    regions: ["africa", "", "", ""],
    iso2: "mw",
    countryCode: 265,
    dialCode: 265,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Malawi (+265)",
    mainCode: null,
  },
  {
    name: "Malaysia",
    regions: ["asia", "", "", ""],
    iso2: "my",
    countryCode: 60,
    dialCode: 60,
    format: "+.. ..-....-....",
    priority: 0,
    n: "Malaysia (+60)",
    mainCode: null,
  },
  {
    name: "Maldives",
    regions: ["asia", "", "", ""],
    iso2: "mv",
    countryCode: 960,
    dialCode: 960,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Maldives (+960)",
    mainCode: null,
  },
  {
    name: "Mali",
    regions: ["africa", "", "", ""],
    iso2: "ml",
    countryCode: 223,
    dialCode: 223,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Mali (+223)",
    mainCode: null,
  },
  {
    name: "Malta",
    regions: ["europe", "eu-union", "", ""],
    iso2: "mt",
    countryCode: 356,
    dialCode: 356,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Malta (+356)",
    mainCode: null,
  },
  {
    name: "Marshall Islands",
    regions: ["oceania", "", "", ""],
    iso2: "mh",
    countryCode: 692,
    dialCode: 692,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Marshall Islands (+692)",
    mainCode: null,
  },
  {
    name: "Martinique",
    regions: ["america", "carribean", "", ""],
    iso2: "mq",
    countryCode: 596,
    dialCode: 596,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Martinique (+596)",
    mainCode: null,
  },
  {
    name: "Mauritania",
    regions: ["africa", "", "", ""],
    iso2: "mr",
    countryCode: 222,
    dialCode: 222,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Mauritania (‫موريتانيا‬‎)(+222‬‎)",
    mainCode: null,
  },
  {
    name: "Mauritius",
    regions: ["africa", "", "", ""],
    iso2: "mu",
    countryCode: 230,
    dialCode: 230,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Mauritius (Moris)(+230)",
    mainCode: null,
  },
  {
    name: "Mexico",
    regions: ["america", "central-america", "", ""],
    iso2: "mx",
    countryCode: 52,
    dialCode: 52,
    format: "+.. ... ... ....",
    priority: 0,
    n: "Mexico (México)(+52)",
    mainCode: true,
  },
  {
    name: "Micronesia",
    regions: ["oceania", "", "", ""],
    iso2: "fm",
    countryCode: 691,
    dialCode: 691,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Micronesia (+691)",
    mainCode: null,
  },
  {
    name: "Moldova",
    regions: ["europe", "", "", ""],
    iso2: "md",
    countryCode: 373,
    dialCode: 373,
    format: "+... (..) ..-..-..",
    priority: 0,
    n: "Moldova (Republica Moldova)(+373)",
    mainCode: null,
  },
  {
    name: "Monaco",
    regions: ["europe", "", "", ""],
    iso2: "mc",
    countryCode: 377,
    dialCode: 377,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Monaco (+377)",
    mainCode: null,
  },
  {
    name: "Mongolia",
    regions: ["asia", "", "", ""],
    iso2: "mn",
    countryCode: 976,
    dialCode: 976,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Mongolia (Монгол)(+976)",
    mainCode: null,
  },
  {
    name: "Montenegro",
    regions: ["europe", "ex-yugos", "", ""],
    iso2: "me",
    countryCode: 382,
    dialCode: 382,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Montenegro (Crna Gora)(+382)",
    mainCode: null,
  },
  {
    name: "Morocco",
    regions: ["africa", "north-africa", "", ""],
    iso2: "ma",
    countryCode: 212,
    dialCode: 212,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Morocco (‫المغرب‬‎)(+212‬‎)",
    mainCode: null,
  },
  {
    name: "Mozambique",
    regions: ["africa", "", "", ""],
    iso2: "mz",
    countryCode: 258,
    dialCode: 258,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Mozambique (Moçambique)(+258)",
    mainCode: null,
  },
  {
    name: "Myanmar",
    regions: ["asia", "", "", ""],
    iso2: "mm",
    countryCode: 95,
    dialCode: 95,
    format: "+.. ... ... ... ... ..",
    priority: 0,
    n: "Myanmar (Burma) (မြန်မာ) (+95)",
    mainCode: null,
  },
  {
    name: "Namibia",
    regions: ["africa", "", "", ""],
    iso2: "na",
    countryCode: 264,
    dialCode: 264,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Namibia (Namibië)(+264)",
    mainCode: null,
  },
  {
    name: "Nauru",
    regions: ["africa", "", "", ""],
    iso2: "nr",
    countryCode: 674,
    dialCode: 674,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Nauru (+674)",
    mainCode: null,
  },
  {
    name: "Nepal",
    regions: ["asia", "", "", ""],
    iso2: "np",
    countryCode: 977,
    dialCode: 977,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Nepal (नेपाल)(+977)",
    mainCode: null,
  },
  {
    name: "Netherlands",
    regions: ["europe", "eu-union", "", ""],
    iso2: "nl",
    countryCode: 31,
    dialCode: 31,
    format: "+.. .. ........",
    priority: 0,
    n: "Netherlands (Nederland)(+31)",
    mainCode: null,
  },
  {
    name: "New Caledonia",
    regions: ["oceania", "", "", ""],
    iso2: "nc",
    countryCode: 687,
    dialCode: 687,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "New Caledonia (Nouvelle-Calédonie)(+687)",
    mainCode: null,
  },
  {
    name: "New Zealand",
    regions: ["oceania", "", "", ""],
    iso2: "nz",
    countryCode: 64,
    dialCode: 64,
    format: "+.. ...-...-....",
    priority: 0,
    n: "New Zealand (+64)",
    mainCode: null,
  },
  {
    name: "Nicaragua",
    regions: ["america", "central-america", "", ""],
    iso2: "ni",
    countryCode: 505,
    dialCode: 505,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Nicaragua (+505)",
    mainCode: null,
  },
  {
    name: "Niger",
    regions: ["africa", "", "", ""],
    iso2: "ne",
    countryCode: 227,
    dialCode: 227,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Niger (Nijar)(+227)",
    mainCode: null,
  },
  {
    name: "Nigeria",
    regions: ["africa", "", "", ""],
    iso2: "ng",
    countryCode: 234,
    dialCode: 234,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Nigeria (+234)",
    mainCode: null,
  },
  {
    name: "North Korea",
    regions: ["asia", "", "", ""],
    iso2: "kp",
    countryCode: 850,
    dialCode: 850,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "North Korea (조선 민주주의 인민 공화국)(+850)",
    mainCode: null,
  },
  {
    name: "Norway",
    regions: ["europe", "baltic", "", ""],
    iso2: "no",
    countryCode: 47,
    dialCode: 47,
    format: "+.. ... .. ...",
    priority: 0,
    n: "Norway (Norge)(+47)",
    mainCode: null,
  },
  {
    name: "Oman",
    regions: ["middle-east", "", "", ""],
    iso2: "om",
    countryCode: 968,
    dialCode: 968,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Oman (‫عُمان‬‎)(+968‬‎)",
    mainCode: null,
  },
  {
    name: "Pakistan",
    regions: ["asia", "", "", ""],
    iso2: "pk",
    countryCode: 92,
    dialCode: 92,
    format: "+.. ...-.......",
    priority: 0,
    n: "Pakistan (‫پاکستان‬‎)(+92‬‎)",
    mainCode: null,
  },
  {
    name: "Palau",
    regions: ["oceania", "", "", ""],
    iso2: "pw",
    countryCode: 680,
    dialCode: 680,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Palau (+680)",
    mainCode: null,
  },
  {
    name: "Palestine",
    regions: ["middle-east", "", "", ""],
    iso2: "ps",
    countryCode: 970,
    dialCode: 970,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Palestine (‫فلسطين‬‎)(+970‬‎)",
    mainCode: null,
  },
  {
    name: "Panama",
    regions: ["america", "central-america", "", ""],
    iso2: "pa",
    countryCode: 507,
    dialCode: 507,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Panama (Panamá)(+507)",
    mainCode: null,
  },
  {
    name: "Papua New Guinea",
    regions: ["oceania", "", "", ""],
    iso2: "pg",
    countryCode: 675,
    dialCode: 675,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Papua New Guinea (+675)",
    mainCode: null,
  },
  {
    name: "Paraguay",
    regions: ["america", "south-america", "", ""],
    iso2: "py",
    countryCode: 595,
    dialCode: 595,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Paraguay (+595)",
    mainCode: null,
  },
  {
    name: "Peru",
    regions: ["america", "south-america", "", ""],
    iso2: "pe",
    countryCode: 51,
    dialCode: 51,
    format: "+.. ... ... ... ... ..",
    priority: 0,
    n: "Peru (Perú)(+51)",
    mainCode: null,
  },
  {
    name: "Philippines",
    regions: ["asia", "", "", ""],
    iso2: "ph",
    countryCode: 63,
    dialCode: 63,
    format: "+.. .... .......",
    priority: 0,
    n: "Philippines (+63)",
    mainCode: null,
  },
  {
    name: "Poland",
    regions: ["europe", "eu-union", "baltic", ""],
    iso2: "pl",
    countryCode: 48,
    dialCode: 48,
    format: "+.. ...-...-...",
    priority: 0,
    n: "Poland (Polska)(+48)",
    mainCode: null,
  },
  {
    name: "Portugal",
    regions: ["europe", "eu-union", "", ""],
    iso2: "pt",
    countryCode: 351,
    dialCode: 351,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Portugal (+351)",
    mainCode: null,
  },
  {
    name: "Puerto Rico",
    regions: ["america", "carribean", "", ""],
    iso2: "pr",
    countryCode: 1,
    dialCode: 1,
    format: "+. ... ... ... ... ..",
    priority: 3,
    n: "Puerto Rico (+1787)",
    mainCode: true,
  },
  {
    name: "Qatar",
    regions: ["middle-east", "", "", ""],
    iso2: "qa",
    countryCode: 974,
    dialCode: 974,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Qatar (‫قطر‬‎)(+974‬‎)",
    mainCode: null,
  },
  {
    name: "Réunion",
    regions: ["africa", "", "", ""],
    iso2: "re",
    countryCode: 262,
    dialCode: 262,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Réunion (La Réunion)(+262)",
    mainCode: null,
  },
  {
    name: "Romania",
    regions: ["europe", "eu-union", "", ""],
    iso2: "ro",
    countryCode: 40,
    dialCode: 40,
    format: "+.. ... ... ... ... ..",
    priority: 0,
    n: "Romania (România)(+40)",
    mainCode: null,
  },
  {
    name: "Russia",
    regions: ["europe", "asia", "ex-ussr", "baltic"],
    iso2: "ru",
    countryCode: 7,
    dialCode: 7,
    format: "+. (...) ...-..-..",
    priority: 0,
    n: "Russia (Россия)(+70)",
    mainCode: null,
  },
  {
    name: "Rwanda",
    regions: ["africa", "", "", ""],
    iso2: "rw",
    countryCode: 250,
    dialCode: 250,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Rwanda (+250)",
    mainCode: null,
  },
  {
    name: "Saint Kitts and Nevis",
    regions: ["america", "carribean", "", ""],
    iso2: "kn",
    countryCode: 1869,
    dialCode: 1869,
    format: "+.... ... ... ... ... ..",
    priority: 0,
    n: "Saint Kitts and Nevis (+1869)",
    mainCode: null,
  },
  {
    name: "Saint Lucia",
    regions: ["america", "carribean", "", ""],
    iso2: "lc",
    countryCode: 1758,
    dialCode: 1758,
    format: "+.... ... ... ... ... ..",
    priority: 0,
    n: "Saint Lucia (+1758)",
    mainCode: null,
  },
  {
    name: "Saint Vincent and the Grenadines",
    regions: ["america", "carribean", "", ""],
    iso2: "vc",
    countryCode: 1784,
    dialCode: 1784,
    format: "+.... ... ... ... ... ..",
    priority: 0,
    n: "Saint Vincent and the Grenadines(+1784)",
    mainCode: null,
  },
  {
    name: "Samoa",
    regions: ["oceania", "", "", ""],
    iso2: "ws",
    countryCode: 685,
    dialCode: 685,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Samoa (+684)",
    mainCode: null,
  },
  {
    name: "San Marino",
    regions: ["europe", "", "", ""],
    iso2: "sm",
    countryCode: 378,
    dialCode: 378,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "San Marino (+378)",
    mainCode: null,
  },
  {
    name: "São Tomé and Príncipe",
    regions: ["africa", "", "", ""],
    iso2: "st",
    countryCode: 239,
    dialCode: 239,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "São Tomé and Príncipe (São Tomé e Príncipe)(+239)",
    mainCode: null,
  },
  {
    name: "Saudi Arabia",
    regions: ["middle-east", "", "", ""],
    iso2: "sa",
    countryCode: 966,
    dialCode: 966,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Saudi Arabia (‫المملكة العربية السعودية‬‎)(+966)",
    mainCode: null,
  },
  {
    name: "Senegal",
    regions: ["africa", "", "", ""],
    iso2: "sn",
    countryCode: 221,
    dialCode: 221,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Senegal (Sénégal)(+221)",
    mainCode: null,
  },
  {
    name: "Serbia",
    regions: ["europe", "ex-yugos", "", ""],
    iso2: "rs",
    countryCode: 381,
    dialCode: 381,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Serbia (Србија)(+381)",
    mainCode: null,
  },
  {
    name: "Seychelles",
    regions: ["africa", "", "", ""],
    iso2: "sc",
    countryCode: 248,
    dialCode: 248,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Seychelles (+248)",
    mainCode: null,
  },
  {
    name: "Sierra Leone",
    regions: ["africa", "", "", ""],
    iso2: "sl",
    countryCode: 232,
    dialCode: 232,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Sierra Leone (+232)",
    mainCode: null,
  },
  {
    name: "Singapore",
    regions: ["asia", "", "", ""],
    iso2: "sg",
    countryCode: 65,
    dialCode: 65,
    format: "+.. ....-....",
    priority: 0,
    n: "Singapore (+65)",
    mainCode: null,
  },
  {
    name: "Slovakia",
    regions: ["europe", "eu-union", "", ""],
    iso2: "sk",
    countryCode: 421,
    dialCode: 421,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Slovakia (Slovensko)(+421)",
    mainCode: null,
  },
  {
    name: "Slovenia",
    regions: ["europe", "eu-union", "ex-yugos", ""],
    iso2: "si",
    countryCode: 386,
    dialCode: 386,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Slovenia (Slovenija)(+386)",
    mainCode: null,
  },
  {
    name: "Solomon Islands",
    regions: ["oceania", "", "", ""],
    iso2: "sb",
    countryCode: 677,
    dialCode: 677,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Solomon Islands (+677)",
    mainCode: null,
  },
  {
    name: "Somalia",
    regions: ["africa", "", "", ""],
    iso2: "so",
    countryCode: 252,
    dialCode: 252,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Somalia (Soomaaliya)(+252)",
    mainCode: null,
  },
  {
    name: "South Africa",
    regions: ["africa", "", "", ""],
    iso2: "za",
    countryCode: 27,
    dialCode: 27,
    format: "+.. ... ... ... ... ..",
    priority: 0,
    n: "South Africa (+27)",
    mainCode: null,
  },
  {
    name: "South Korea",
    regions: ["asia", "", "", ""],
    iso2: "kr",
    countryCode: 82,
    dialCode: 82,
    format: "+.. ... .... ....",
    priority: 0,
    n: "South Korea (대한민국)(+82)",
    mainCode: null,
  },
  {
    name: "South Sudan",
    regions: ["africa", "north-africa", "", ""],
    iso2: "ss",
    countryCode: 211,
    dialCode: 211,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "South Sudan (‫جنوب السودان‬‎)(+211)",
    mainCode: null,
  },
  {
    name: "Spain",
    regions: ["europe", "eu-union", "", ""],
    iso2: "es",
    countryCode: 34,
    dialCode: 34,
    format: "+.. ... ... ...",
    priority: 0,
    n: "Spain (España)(+34)",
    mainCode: null,
  },
  {
    name: "Sri Lanka",
    regions: ["asia", "", "", ""],
    iso2: "lk",
    countryCode: 94,
    dialCode: 94,
    format: "+.. ... ... ... ... ..",
    priority: 0,
    n: "Sri Lanka (ශ්‍රී ලංකාව)(+94)",
    mainCode: null,
  },
  {
    name: "Sudan",
    regions: ["africa", "", "", ""],
    iso2: "sd",
    countryCode: 249,
    dialCode: 249,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Sudan (‫السودان‬‎)(+249‬‎)",
    mainCode: null,
  },
  {
    name: "Suriname",
    regions: ["america", "south-america", "", ""],
    iso2: "sr",
    countryCode: 597,
    dialCode: 597,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Suriname (+597)",
    mainCode: null,
  },
  {
    name: "Swaziland",
    regions: ["africa", "", "", ""],
    iso2: "sz",
    countryCode: 268,
    dialCode: 268,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Swaziland (Kingdom of eSwatini)(+268)",
    mainCode: null,
  },
  {
    name: "Sweden",
    regions: ["europe", "eu-union", "baltic", ""],
    iso2: "se",
    countryCode: 46,
    dialCode: 46,
    format: "+.. (...) ...-...",
    priority: 0,
    n: "Sweden (Sverige)(+46)",
    mainCode: null,
  },
  {
    name: "Switzerland",
    regions: ["europe", "", "", ""],
    iso2: "ch",
    countryCode: 41,
    dialCode: 41,
    format: "+.. .. ... .. ..",
    priority: 0,
    n: "Switzerland (Schweiz/Suisse/Svizzera)(+41)",
    mainCode: null,
  },
  {
    name: "Syria",
    regions: ["middle-east", "", "", ""],
    iso2: "sy",
    countryCode: 963,
    dialCode: 963,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Syria (‫سوريا‬‎)(+963‬‎)",
    mainCode: null,
  },
  {
    name: "Taiwan",
    regions: ["asia", "", "", ""],
    iso2: "tw",
    countryCode: 886,
    dialCode: 886,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Taiwan (台灣)(+886)",
    mainCode: null,
  },
  {
    name: "Tajikistan",
    regions: ["asia", "ex-ussr", "", ""],
    iso2: "tj",
    countryCode: 992,
    dialCode: 992,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Tajikistan (+992)",
    mainCode: null,
  },
  {
    name: "Tanzania",
    regions: ["africa", "", "", ""],
    iso2: "tz",
    countryCode: 255,
    dialCode: 255,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Tanzania (+255)",
    mainCode: null,
  },
  {
    name: "Thailand",
    regions: ["asia", "", "", ""],
    iso2: "th",
    countryCode: 66,
    dialCode: 66,
    format: "+.. ... ... ... ... ..",
    priority: 0,
    n: "Thailand (ไทย)(+66)",
    mainCode: null,
  },
  {
    name: "Timor-Leste",
    regions: ["asia", "", "", ""],
    iso2: "tl",
    countryCode: 670,
    dialCode: 670,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Timor-Leste (+670)",
    mainCode: null,
  },
  {
    name: "Togo",
    regions: ["africa", "", "", ""],
    iso2: "tg",
    countryCode: 228,
    dialCode: 228,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Togo (+228)",
    mainCode: null,
  },
  {
    name: "Tonga",
    regions: ["oceania", "", "", ""],
    iso2: "to",
    countryCode: 676,
    dialCode: 676,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Tonga (+676)",
    mainCode: null,
  },
  {
    name: "Trinidad and Tobago",
    regions: ["america", "carribean", "", ""],
    iso2: "tt",
    countryCode: 1868,
    dialCode: 1868,
    format: "+.... ... ... ... ... ..",
    priority: 0,
    n: "Trinidad and Tobago (+1868)",
    mainCode: null,
  },
  {
    name: "Tunisia",
    regions: ["africa", "north-africa", "", ""],
    iso2: "tn",
    countryCode: 216,
    dialCode: 216,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Tunisia (‫تونس‬‎)(+216‬‎)",
    mainCode: null,
  },
  {
    name: "Turkey",
    regions: ["europe", "", "", ""],
    iso2: "tr",
    countryCode: 90,
    dialCode: 90,
    format: "+.. ... ... .. ..",
    priority: 0,
    n: "Turkey (Türkiye)(+90)",
    mainCode: null,
  },
  {
    name: "Turkmenistan",
    regions: ["asia", "ex-ussr", "", ""],
    iso2: "tm",
    countryCode: 993,
    dialCode: 993,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Turkmenistan (+7370)",
    mainCode: null,
  },
  {
    name: "Tuvalu",
    regions: ["asia", "", "", ""],
    iso2: "tv",
    countryCode: 688,
    dialCode: 688,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Tuvalu (+688)",
    mainCode: null,
  },
  {
    name: "Uganda",
    regions: ["africa", "", "", ""],
    iso2: "ug",
    countryCode: 256,
    dialCode: 256,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Uganda (+256)",
    mainCode: null,
  },
  {
    name: "Ukraine",
    regions: ["europe", "ex-ussr", "", ""],
    iso2: "ua",
    countryCode: 380,
    dialCode: 380,
    format: "+... (..) ... .. ..",
    priority: 0,
    n: "Ukraine (Україна)(+380)",
    mainCode: null,
  },
  {
    name: "United Arab Emirates",
    regions: ["middle-east", "", "", ""],
    iso2: "ae",
    countryCode: 971,
    dialCode: 971,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "United Arab Emirates (‫الإمارات العربية المتحدة‬‎)(+971‬‎)",
    mainCode: null,
  },
  {
    name: "United Kingdom",
    regions: ["europe", "eu-union", "", ""],
    iso2: "gb",
    countryCode: 44,
    dialCode: 44,
    format: "+.. .... ......",
    priority: 0,
    n: "United Kingdom (UK)(+44)",
    mainCode: null,
  },
  {
    name: "United States",
    regions: ["america", "north-america", "", ""],
    iso2: "us",
    countryCode: 1,
    dialCode: 1,
    format: "+. (...) ...-....",
    priority: 0,
    n: "United States (USA)(+1)",
    mainCode: true,
  },
  {
    name: "Uruguay",
    regions: ["america", "south-america", "", ""],
    iso2: "uy",
    countryCode: 598,
    dialCode: 598,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Uruguay (+598)",
    mainCode: null,
  },
  {
    name: "Uzbekistan",
    regions: ["asia", "ex-ussr", "", ""],
    iso2: "uz",
    countryCode: 998,
    dialCode: 998,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Uzbekistan (Oʻzbekiston)(+998)",
    mainCode: null,
  },
  {
    name: "Vanuatu",
    regions: ["oceania", "", "", ""],
    iso2: "vu",
    countryCode: 678,
    dialCode: 678,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Vanuatu (+678)",
    mainCode: null,
  },
  {
    name: "Vatican City",
    regions: ["europe", "", "", ""],
    iso2: "va",
    countryCode: 39,
    dialCode: 39,
    format: "+.. .. .... ....",
    priority: 1,
    n: "Vatican City (Città del Vaticano)(+39)",
    mainCode: null,
  },
  {
    name: "Venezuela",
    regions: ["america", "south-america", "", ""],
    iso2: "ve",
    countryCode: 58,
    dialCode: 58,
    format: "+.. ... ... ... ... ..",
    priority: 0,
    n: "Venezuela (+58)",
    mainCode: null,
  },
  {
    name: "Vietnam",
    regions: ["asia", "", "", ""],
    iso2: "vn",
    countryCode: 84,
    dialCode: 84,
    format: "+.. ... ... ... ... ..",
    priority: 0,
    n: "Vietnam (Việt Nam)(+84)",
    mainCode: null,
  },
  {
    name: "Yemen",
    regions: ["middle-east", "", "", ""],
    iso2: "ye",
    countryCode: 967,
    dialCode: 967,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Yemen (‫اليمن‬‎)(+967‬‎)",
    mainCode: null,
  },
  {
    name: "Zambia",
    regions: ["africa", "", "", ""],
    iso2: "zm",
    countryCode: 260,
    dialCode: 260,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Zambia (+260)",
    mainCode: null,
  },
  {
    name: "Zimbabwe",
    regions: ["africa", "", "", ""],
    iso2: "zw",
    countryCode: 263,
    dialCode: 263,
    format: "+... ... ... ... ... ..",
    priority: 0,
    n: "Zimbabwe (+263)",
    mainCode: null,
  },
];
export default countriesData;